import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from sqlalchemy import String, Integer, DateTime, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base

class Document(Base):
    __tablename__ = "corpstage_documents"

    # Primary key UUID track reference
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    
    # Critical tenant ID separation for isolation and Row-Level Security (RLS) enforcement
    tenant_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    
    # File specifications
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False)
    content_type: Mapped[str] = mapped_column(String(100), nullable=False)
    storage_path: Mapped[str] = mapped_column(String(1024), nullable=False)  # URI to Azure evidence container/AWS
    
    # Categories for schema validation
    document_type: Mapped[str] = mapped_column(String(50), nullable=False)  # i.e. esg_report, annual_report
    
    # State flags
    status: Mapped[str] = mapped_column(String(50), default="uploaded", nullable=False)  # uploaded, ocr_pending, ocr_processing, ocr_completed, ocr_failed
    
    # OCR Async task ID generated by the broker/queue
    ocr_task_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    # JSON payloads representing custom ESG attributes, confidence score, or extraction tables
    metadata_json: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    extracted_data_json: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    
    # Dynamic lifecycle timelines
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Optional backref to transaction upload session records
    upload_tracker_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("corpstage_upload_trackers.id", ondelete="SET NULL"), nullable=True)
    upload_session = relationship("UploadTracker", back_populates="documents")
