-- =============================================================================
-- 03_seed_r001_data.sql
-- Aurex AuthService — R-001 Seed Data
-- =============================================================================
-- PURPOSE
--   Seeds the 6 R-001 roles, 12 permissions, and 42 role-permission mappings
--   into the tables created by the Alembic migration (8fac154e79e2).
--   Run ONLY after the Alembic migration has been applied successfully.
--
-- UUID GENERATION STRATEGY
--   Role and permission UUIDs are deterministic (uuid5 with a fixed Aurex
--   seed namespace). This means the script is idempotent when used with the
--   ON CONFLICT clause — re-running it will not create duplicate rows.
--   Role-permission junction UUIDs are generated by gen_random_uuid() since
--   the surrogate PK on that table has no external references.
--
-- SEED UUID REFERENCE
--   Roles:
--     PLATFORM_ADMIN  9524d250-fe5e-5334-845b-18d547a5b59c
--     ORG_ADMIN       c0d893dd-834a-539a-b0b9-cea32d756c9e
--     ESG_MANAGER     2b3bda96-a1d2-55ae-8cc5-09653a6c795e
--     AUDITOR         39a005f5-418a-5b1c-b011-2120aa4b1b87
--     SUPPLIER_ADMIN  439b0997-aee6-57ec-b6a1-a9aa799dcfbb
--     BOARD_MEMBER    f401a452-c1ab-5df0-82fb-68ae7f8b9290
--
--   Permissions:
--     DOCUMENT_READ   2e02360a-7a9c-5790-a980-0f4351e3a0ab
--     DOCUMENT_WRITE  06f4f2f3-94a3-5e23-b23f-cbb048f9a46a
--     METRIC_READ     688d3f58-f57d-5cd6-8c7d-de663fecd267
--     METRIC_EDIT     f94017b0-8f30-5798-9281-823bc4c54536
--     REPORT_READ     2a4f927d-6e37-558a-95b5-9ddea411a6da
--     REPORT_EXPORT   52dbd32c-7b47-56ab-8726-292ba442d879
--     SCORE_VIEW      896a1d45-249b-5611-9813-715860a4a29d
--     ORG_READ        b54d3558-195d-5596-a6b5-c66a863fbe15
--     ORG_WRITE       ae67473a-990b-5d14-a5af-8e6fad3540ec
--     USER_READ       d4705417-3fc1-5044-916f-e57ae9b8c1c7
--     USER_WRITE      dc2e1856-cee9-5cd6-971c-2f0d0d82ddca
--     AI_EXTRACT      09ee8ea0-173c-5a33-9e4d-22de6b6244c6
--
-- HOW TO RUN
--   docker exec -it aurex-postgres psql -U postgres -d aurex \
--     -f /path/to/03_seed_r001_data.sql
-- =============================================================================

\echo ''
\echo '======================================='
\echo 'STEP 3 — SEED R-001 DATA'
\echo '======================================='
\echo ''

BEGIN;

-- =============================================================================
-- BLOCK A: Roles (6 rows)
-- =============================================================================

\echo 'Seeding roles ...'

INSERT INTO roles (
    id,
    role_code,
    role_name,
    description,
    is_system_role,
    created_at,
    updated_at
)
VALUES
    -- -------------------------------------------------------------------------
    -- PLATFORM_ADMIN
    -- System-level role. Manages the Aurex platform itself.
    -- is_system_role = true: cannot be deleted or modified by org admins.
    -- -------------------------------------------------------------------------
    (
        '9524d250-fe5e-5334-845b-18d547a5b59c',
        'PLATFORM_ADMIN',
        'Platform Administrator',
        'Aurex platform operator. Manages all organizations, system configuration, and platform-level settings. Operates across all organization boundaries.',
        true,
        NOW(),
        NULL
    ),

    -- -------------------------------------------------------------------------
    -- ORG_ADMIN
    -- Full control within a single organization. The primary admin role.
    -- -------------------------------------------------------------------------
    (
        'c0d893dd-834a-539a-b0b9-cea32d756c9e',
        'ORG_ADMIN',
        'Organization Administrator',
        'Full operational control within a single organization. Manages members, workspaces, documents, and license allocation.',
        false,
        NOW(),
        NULL
    ),

    -- -------------------------------------------------------------------------
    -- ESG_MANAGER
    -- Manages the ESG program. Primary operational role for sustainability work.
    -- -------------------------------------------------------------------------
    (
        '2b3bda96-a1d2-55ae-8cc5-09653a6c795e',
        'ESG_MANAGER',
        'ESG Manager',
        'Manages the organization ESG program. Validates sustainability data, compiles reports, oversees data quality, and runs AI extraction workflows.',
        false,
        NOW(),
        NULL
    ),

    -- -------------------------------------------------------------------------
    -- AUDITOR
    -- External read-only specialist. No write access to any data.
    -- -------------------------------------------------------------------------
    (
        '39a005f5-418a-5b1c-b011-2120aa4b1b87',
        'AUDITOR',
        'Auditor',
        'External read-only audit specialist. Verifies documentation, metrics, and evidence trails. No write access to any data.',
        false,
        NOW(),
        NULL
    ),

    -- -------------------------------------------------------------------------
    -- SUPPLIER_ADMIN
    -- Supplier representative. Document upload only. No ESG data access.
    -- -------------------------------------------------------------------------
    (
        '439b0997-aee6-57ec-b6a1-a9aa799dcfbb',
        'SUPPLIER_ADMIN',
        'Supplier Administrator',
        'Supplier organization representative. Uploads evidence and manages documents on behalf of the supplier. No access to internal ESG metrics or reports.',
        false,
        NOW(),
        NULL
    ),

    -- -------------------------------------------------------------------------
    -- BOARD_MEMBER
    -- Executive read access. High-level dashboards and reports only.
    -- -------------------------------------------------------------------------
    (
        'f401a452-c1ab-5df0-82fb-68ae7f8b9290',
        'BOARD_MEMBER',
        'Board Member',
        'Executive-level read access to dashboards, ESG scores, and reports. No operational or data entry access.',
        false,
        NOW(),
        NULL
    )

ON CONFLICT (role_code) DO NOTHING;

\echo 'OK: 6 roles inserted'

-- =============================================================================
-- BLOCK B: Permissions (12 rows, 4 domains)
-- =============================================================================

\echo 'Seeding permissions ...'

INSERT INTO permissions (
    id,
    permission_code,
    permission_name,
    description,
    created_at
)
VALUES
    -- Documents ------------------------------------------------------------------
    (
        '2e02360a-7a9c-5790-a980-0f4351e3a0ab',
        'DOCUMENT_READ',
        'Read Documents',
        'View uploaded documents and their metadata.',
        NOW()
    ),
    (
        '06f4f2f3-94a3-5e23-b23f-cbb048f9a46a',
        'DOCUMENT_WRITE',
        'Write Documents',
        'Upload, update, and manage documents in evidence storage.',
        NOW()
    ),
    -- Metrics --------------------------------------------------------------------
    (
        '688d3f58-f57d-5cd6-8c7d-de663fecd267',
        'METRIC_READ',
        'Read Metrics',
        'Read ESG metrics, sustainability data values, and historical records.',
        NOW()
    ),
    (
        'f94017b0-8f30-5798-9281-823bc4c54536',
        'METRIC_EDIT',
        'Edit Metrics',
        'Create and modify metric values and sustainability data entries.',
        NOW()
    ),
    -- Reports --------------------------------------------------------------------
    (
        '2a4f927d-6e37-558a-95b5-9ddea411a6da',
        'REPORT_READ',
        'Read Reports',
        'View ESG reports, analytics, and draft disclosure documents.',
        NOW()
    ),
    (
        '52dbd32c-7b47-56ab-8726-292ba442d879',
        'REPORT_EXPORT',
        'Export Reports',
        'Sign off and export finalized ESG disclosure documents.',
        NOW()
    ),
    -- Scores ---------------------------------------------------------------------
    (
        '896a1d45-249b-5611-9813-715860a4a29d',
        'SCORE_VIEW',
        'View Scores',
        'View computed ESG scores and assessment ratings.',
        NOW()
    ),
    -- Organization ---------------------------------------------------------------
    (
        'b54d3558-195d-5596-a6b5-c66a863fbe15',
        'ORG_READ',
        'Read Organization',
        'Read organization settings, configuration, and member directory.',
        NOW()
    ),
    (
        'ae67473a-990b-5d14-a5af-8e6fad3540ec',
        'ORG_WRITE',
        'Write Organization',
        'Modify organization settings, configuration, and manage members.',
        NOW()
    ),
    -- Users ----------------------------------------------------------------------
    (
        'd4705417-3fc1-5044-916f-e57ae9b8c1c7',
        'USER_READ',
        'Read Users',
        'View user directory and account details.',
        NOW()
    ),
    (
        'dc2e1856-cee9-5cd6-971c-2f0d0d82ddca',
        'USER_WRITE',
        'Write Users',
        'Create, update, and deactivate user accounts and credentials.',
        NOW()
    ),
    -- AI -------------------------------------------------------------------------
    (
        '09ee8ea0-173c-5a33-9e4d-22de6b6244c6',
        'AI_EXTRACT',
        'Run AI Extraction',
        'Invoke AI extraction pipelines on uploaded documents to discover sustainability data.',
        NOW()
    )

ON CONFLICT (permission_code) DO NOTHING;

\echo 'OK: 12 permissions inserted'

-- =============================================================================
-- BLOCK C: Role-Permission Matrix (42 rows)
--
-- Matrix summary:
--   PLATFORM_ADMIN  12  all permissions
--   ORG_ADMIN       12  all permissions
--   ESG_MANAGER      8  no org/user management
--   AUDITOR          4  read-only
--   SUPPLIER_ADMIN   2  documents only
--   BOARD_MEMBER     4  executive read
-- =============================================================================

\echo 'Seeding role_permissions ...'

INSERT INTO role_permissions (id, role_id, permission_id, created_at)
VALUES

    -- =========================================================================
    -- PLATFORM_ADMIN (12 permissions — all)
    -- =========================================================================
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '2e02360a-7a9c-5790-a980-0f4351e3a0ab', NOW()),  -- DOCUMENT_READ
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '06f4f2f3-94a3-5e23-b23f-cbb048f9a46a', NOW()),  -- DOCUMENT_WRITE
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '688d3f58-f57d-5cd6-8c7d-de663fecd267', NOW()),  -- METRIC_READ
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', 'f94017b0-8f30-5798-9281-823bc4c54536', NOW()),  -- METRIC_EDIT
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '2a4f927d-6e37-558a-95b5-9ddea411a6da', NOW()),  -- REPORT_READ
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '52dbd32c-7b47-56ab-8726-292ba442d879', NOW()),  -- REPORT_EXPORT
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '896a1d45-249b-5611-9813-715860a4a29d', NOW()),  -- SCORE_VIEW
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', 'b54d3558-195d-5596-a6b5-c66a863fbe15', NOW()),  -- ORG_READ
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', 'ae67473a-990b-5d14-a5af-8e6fad3540ec', NOW()),  -- ORG_WRITE
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', 'd4705417-3fc1-5044-916f-e57ae9b8c1c7', NOW()),  -- USER_READ
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', 'dc2e1856-cee9-5cd6-971c-2f0d0d82ddca', NOW()),  -- USER_WRITE
    (gen_random_uuid(), '9524d250-fe5e-5334-845b-18d547a5b59c', '09ee8ea0-173c-5a33-9e4d-22de6b6244c6', NOW()),  -- AI_EXTRACT

    -- =========================================================================
    -- ORG_ADMIN (12 permissions — all)
    -- =========================================================================
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '2e02360a-7a9c-5790-a980-0f4351e3a0ab', NOW()),  -- DOCUMENT_READ
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '06f4f2f3-94a3-5e23-b23f-cbb048f9a46a', NOW()),  -- DOCUMENT_WRITE
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '688d3f58-f57d-5cd6-8c7d-de663fecd267', NOW()),  -- METRIC_READ
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', 'f94017b0-8f30-5798-9281-823bc4c54536', NOW()),  -- METRIC_EDIT
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '2a4f927d-6e37-558a-95b5-9ddea411a6da', NOW()),  -- REPORT_READ
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '52dbd32c-7b47-56ab-8726-292ba442d879', NOW()),  -- REPORT_EXPORT
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '896a1d45-249b-5611-9813-715860a4a29d', NOW()),  -- SCORE_VIEW
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', 'b54d3558-195d-5596-a6b5-c66a863fbe15', NOW()),  -- ORG_READ
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', 'ae67473a-990b-5d14-a5af-8e6fad3540ec', NOW()),  -- ORG_WRITE
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', 'd4705417-3fc1-5044-916f-e57ae9b8c1c7', NOW()),  -- USER_READ
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', 'dc2e1856-cee9-5cd6-971c-2f0d0d82ddca', NOW()),  -- USER_WRITE
    (gen_random_uuid(), 'c0d893dd-834a-539a-b0b9-cea32d756c9e', '09ee8ea0-173c-5a33-9e4d-22de6b6244c6', NOW()),  -- AI_EXTRACT

    -- =========================================================================
    -- ESG_MANAGER (8 permissions — ESG operational, no org/user management)
    -- =========================================================================
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '2e02360a-7a9c-5790-a980-0f4351e3a0ab', NOW()),  -- DOCUMENT_READ
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '06f4f2f3-94a3-5e23-b23f-cbb048f9a46a', NOW()),  -- DOCUMENT_WRITE
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '688d3f58-f57d-5cd6-8c7d-de663fecd267', NOW()),  -- METRIC_READ
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', 'f94017b0-8f30-5798-9281-823bc4c54536', NOW()),  -- METRIC_EDIT
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '2a4f927d-6e37-558a-95b5-9ddea411a6da', NOW()),  -- REPORT_READ
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '52dbd32c-7b47-56ab-8726-292ba442d879', NOW()),  -- REPORT_EXPORT
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '896a1d45-249b-5611-9813-715860a4a29d', NOW()),  -- SCORE_VIEW
    (gen_random_uuid(), '2b3bda96-a1d2-55ae-8cc5-09653a6c795e', '09ee8ea0-173c-5a33-9e4d-22de6b6244c6', NOW()),  -- AI_EXTRACT

    -- =========================================================================
    -- AUDITOR (4 permissions — read-only across all domains they access)
    -- =========================================================================
    (gen_random_uuid(), '39a005f5-418a-5b1c-b011-2120aa4b1b87', '2e02360a-7a9c-5790-a980-0f4351e3a0ab', NOW()),  -- DOCUMENT_READ
    (gen_random_uuid(), '39a005f5-418a-5b1c-b011-2120aa4b1b87', '688d3f58-f57d-5cd6-8c7d-de663fecd267', NOW()),  -- METRIC_READ
    (gen_random_uuid(), '39a005f5-418a-5b1c-b011-2120aa4b1b87', '2a4f927d-6e37-558a-95b5-9ddea411a6da', NOW()),  -- REPORT_READ
    (gen_random_uuid(), '39a005f5-418a-5b1c-b011-2120aa4b1b87', '896a1d45-249b-5611-9813-715860a4a29d', NOW()),  -- SCORE_VIEW

    -- =========================================================================
    -- SUPPLIER_ADMIN (2 permissions — document scope only)
    -- =========================================================================
    (gen_random_uuid(), '439b0997-aee6-57ec-b6a1-a9aa799dcfbb', '2e02360a-7a9c-5790-a980-0f4351e3a0ab', NOW()),  -- DOCUMENT_READ
    (gen_random_uuid(), '439b0997-aee6-57ec-b6a1-a9aa799dcfbb', '06f4f2f3-94a3-5e23-b23f-cbb048f9a46a', NOW()),  -- DOCUMENT_WRITE

    -- =========================================================================
    -- BOARD_MEMBER (4 permissions — executive read)
    -- =========================================================================
    (gen_random_uuid(), 'f401a452-c1ab-5df0-82fb-68ae7f8b9290', '688d3f58-f57d-5cd6-8c7d-de663fecd267', NOW()),  -- METRIC_READ
    (gen_random_uuid(), 'f401a452-c1ab-5df0-82fb-68ae7f8b9290', '2a4f927d-6e37-558a-95b5-9ddea411a6da', NOW()),  -- REPORT_READ
    (gen_random_uuid(), 'f401a452-c1ab-5df0-82fb-68ae7f8b9290', '52dbd32c-7b47-56ab-8726-292ba442d879', NOW()),  -- REPORT_EXPORT
    (gen_random_uuid(), 'f401a452-c1ab-5df0-82fb-68ae7f8b9290', '896a1d45-249b-5611-9813-715860a4a29d', NOW()); -- SCORE_VIEW

\echo 'OK: 42 role_permissions inserted'

COMMIT;

\echo ''
\echo '======================================='
\echo 'STEP 3 COMPLETE — R-001 data seeded'
\echo 'Run 04_post_seed_verify.sql to confirm.'
\echo '======================================='
